"""empty message

Revision ID: 2d36dd539b2e
Revises: cbfc336579ed
Create Date: 2019-12-12 12:34:43.240158

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2d36dd539b2e'
down_revision = 'cbfc336579ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time',
                                     sa.DateTime(),
                                     nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
