"""empty message

Revision ID: 3fff90733a9e
Revises: 84859a486444
Create Date: 2019-12-11 15:05:07.806243

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3fff90733a9e'
down_revision = '84859a486444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    # ### end Alembic commands ###
