"""empty message

Revision ID: 46f3aa839fdf
Revises: 7683faf1e1f1
Create Date: 2019-12-12 10:18:58.419089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f3aa839fdf'
down_revision = '7683faf1e1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Venue_show_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Venue_show_id_fkey', 'Venue', 'Shows', ['show_id'], ['id'])
    # ### end Alembic commands ###
